version: '3'
services:
  web:
    container_name: ga-phperkaigi-todo-api
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - .:/var/www/html:cached
    command: bash -c "sh docker-entrypoint.sh && apache2-foreground"
    ports:
      - "3000:80"
    environment:
      - APP_DEFAULT_LOCALE=ja_JP
      - APP_DEFAULT_TIMEZONE=Asia/Tokyo
      - DATABASE_URL=mysql://root:password@ga-phperkaigi-todo-db/todo_app
      - DATABASE_TEST_URL=mysql://root:password@cakephp-todo-db/test

  db:
    container_name: ga-phperkaigi-todo-db
    build:
      context: .
      dockerfile: ./Docker/mysql/Dockerfile
    volumes:
      - ./Docker/mysql/sqls:/docker-entrypoint-initdb.d
      - ./Docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "13306:3306"
