name: CI

on: pull_request

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.4
          extensions: intl
          coverage: none

      - name: Setup MySQL
        run: mysql -u root -proot -e 'CREATE DATABASE test;'

      - name: Composer install
        working-directory: ./app
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run PHPUnit
        env:
          DATABASE_TEST_URL: mysql://root:root@localhost/test
        working-directory: ./app
        run: vendor/bin/phpunit

      - name: Run PHP_CodeSniffer
        working-directory: ./app
        run: vendor/bin/phpcs -p

      - name: Run PHPStan
        working-directory: ./app
        run: vendor/bin/phpstan analyse
